Repository DEV-dsm/DMG_FrontEnd, pull requests merged in 2023-10, with the labels that each got.

#19 🔀 :: (#19) 로그인 api 연동 및 자잘한 수정
  public/index.html
  src/App.tsx
  src/atom/authAtom.ts
  src/components/auth/LoginInput.tsx
  src/components/common/AuthButton.tsx
  src/components/common/AuthInput.tsx
  src/components/common/Sidebar.tsx
  src/components/hooks/useFileInput.ts
  src/components/hooks/useLogin.ts
  src/constants/index.ts
  src/index.tsx
  src/pages/LoginPage.tsx
  src/router/MainRouter.tsx
  src/utils/Socket.tsx
  src/utils/api/auth/index.ts
  src/utils/axios/index.ts
  src/utils/functions/TokenManager.ts
Labels: api 연동

#21 🔀 :: (#21) Login form 추가 및 로직 변경
  src/components/common/AuthButton.tsx
  src/pages/LoginPage.tsx
Labels: 수정 & 긴급 수정

#27 🔀 :: (#27) 비밀번호 찾기 페이지 api 연동 및 기능 추가
  src/atom/authAtom.ts
  src/components/auth/FindPWInput.tsx
  src/components/common/AuthButton.tsx
  src/components/hooks/useAuthcode.ts
  src/components/hooks/useEmail.ts
  src/constants/index.ts
  src/models/auth.ts
  src/pages/FindPWPage.tsx
  src/utils/api/auth/index.ts
Labels: 기능 추가, api 연동

#35 🎨 :: 문의하기 페이지 퍼블리싱
  src/assets/index.ts
  src/assets/sadFace.svg
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/hooks/useForm.ts
  src/pages/Error.tsx
  src/pages/Inquire.tsx
Labels: 퍼블리싱

#39 🔀 :: (#39) 비밀번호 수정 페이지 퍼블리싱
  package.json
  src/atom/authAtom.ts
  src/components/auth/ChangePWInput.tsx
  src/components/auth/Eye.tsx
  src/components/auth/FindPWInput.tsx
  src/components/common/Sidebar.tsx
  src/components/hooks/useAuthcode.ts
  src/constants/index.ts
  src/models/auth.ts
  src/pages/auth/ChangePWpage.tsx
  src/pages/auth/FindPWPage.tsx
  src/pages/auth/LoginPage.tsx
  src/router/MainRouter.tsx
  yarn.lock
Labels: 퍼블리싱

#43 🔀 :: (#43)파일 Import 방식 변경
  src/assets/sadFace.svg
  src/atom/authAtom.ts
  src/components/auth/ChangePWInput.tsx
  src/components/auth/FindPWInput.tsx
  src/components/common/Sidebar.tsx
  src/components/hooks/apis/useAuthcode.ts
  src/components/hooks/apis/useChangePW.ts
  src/components/hooks/apis/useEmail.ts
  src/components/hooks/apis/useLogin.ts
  src/components/mypage/StudentInfo.tsx
  src/components/mypage/UserDetailInfo.tsx
  src/components/mypage/UserInfoInput.tsx
  src/constants/index.ts
  src/pages/ErrorPage.tsx
  src/pages/auth/ChangePWpage.tsx
  src/pages/auth/FindPWPage.tsx
  src/pages/auth/LoginPage.tsx
  src/router/MainRouter.tsx
  src/router/ProctedRoute.tsx
  src/utils/api/auth/index.ts
  tsconfig.json
Labels: 수정 & 긴급 수정

#45 🔀 :: (#45) Procted Route 구현
  src/atom/authAtom.ts
  src/components/auth/ChangePWInput.tsx
  src/components/auth/FindPWInput.tsx
  src/components/hooks/apis/useAuthcode.ts
  src/components/hooks/apis/useEmail.ts
  src/components/hooks/apis/useLogin.ts
  src/components/mypage/StudentInfo.tsx
  src/components/mypage/UserDetailInfo.tsx
  src/components/mypage/UserInfoInput.tsx
  src/pages/auth/ChangePWpage.tsx
  src/pages/auth/FindPWPage.tsx
  src/pages/auth/LoginPage.tsx
  src/utils/api/auth/index.ts
  tsconfig.json
Labels: 수정 & 긴급 수정

#46 🔀 :: (#46) 유저 Auth 기능 추가
  src/components/auth/ChangePWInput.tsx
  src/components/auth/FindPWInput.tsx
  src/components/auth/LoginInput.tsx
  src/components/common/AuthInput.tsx
  src/components/hooks/apis/useLogin.ts
  src/pages/auth/ChangePWpage.tsx
  src/router/ProctedRoute.tsx
Labels: 기능 추가

#47 🎨 :: UserList 컴포넌트 퍼블리싱
  src/assets/common/index.ts
  src/assets/common/logo1.svg
  src/assets/common/logo2.svg
  src/components/userList/student.tsx
  src/components/userList/teacher.tsx
  src/models/userList.ts
Labels: 퍼블리싱

#49 🔀 :: (#49) UesrList 수정 및 타입 변경
  src/atom/authAtom.ts
  src/components/auth/ChangePWInput.tsx
  src/components/auth/FindPWInput.tsx
  src/components/auth/LoginInput.tsx
  src/components/hooks/apis/useChangePW.ts
  src/components/userList/StudentList.tsx
  src/components/userList/teacher.tsx
  src/constants/index.ts
  src/models/Mypage.ts
  src/models/auth.ts
  src/models/userList.ts
  src/pages/SearchUser.tsx
  src/utils/api/auth/index.ts
Labels: 수정 & 긴급 수정
